version: "2"
services:
  django:
    build: .
    command: gulp.sh
    environment:
      MASTER_PASSWORD: abc123
      PYTHONWARNINGS: ignore
    image: interaction/{{ project_name }}:latest
    links:
      - elasticsearch
      - postgres
      - redis
    ports:
      - "8000:8000"
    # tty: true  # Enable colour output in logs. Disconnects after 60 second timeout. See: https://github.com/docker/compose/issues/3106
    volumes:
      - ./:/opt/{{ project_name }}
      - ./var:/opt/{{ project_name }}/var
  elasticsearch:
    image: interaction/elasticsearch-icu:1
  postgres:
    image: postgres:9.4
  redis:
    command: redis-server --appendonly yes
    image: redis:3-alpine
