django:
  command: runtests.sh
  environment:
    TRAVIS:
  image: interaction/{{ project_name }}:${TAG}
  links:
    - elasticsearch
    - postgres
    - redis
  # tty: true  # Enable colour output in logs. Disconnects after 60 second timeout. See: https://github.com/docker/compose/issues/3106
elasticsearch:
  image: interaction/elasticsearch-icu:1
postgres:
  image: postgres:9.4
redis:
  command: redis-server --appendonly yes
  image: redis:3-alpine
