version: "2"
services:
  django:
    build: .
    # command: gulp.sh
    command: setup-local-env.sh migrate.sh supervisor.sh
    environment:
      PYTHONWARNINGS: ignore
    image: interaction/{{ project_name }}:latest
    links:
      - elasticsearch
      - postgres
      - redis
    ports:
      - "8000:8000"
    # tty: true
    volumes:
      - ./:/opt/{{ project_name }}
      - ./var:/opt/{{ project_name }}/var
  elasticsearch:
    image: interaction/elasticsearch-icu:1
  postgres:
    image: postgres:9.4
  redis:
    image: redis:3
