version: "2"
services:
  django:
    build: .
    command: gulp.sh
    environment:
      # AWS_ACCESS_KEY_ID:
      # AWS_SECRET_ACCESS_KEY:
      # AWS_STORAGE_BUCKET_NAME:
      BASE_SETTINGS_MODULE: develop
      # EMAIL_HOST:
      # EMAIL_HOST_PASSWORD:
      # EMAIL_HOST_USER:
      # MASTER_PASSWORD:
      # NEW_RELIC_CONFIG_FILE:
      # PGDATABASE:
      # PGHOST:
      # PGPASSWORD:
      # PGPORT:
      # PGUSER:
      # SENTRY_DSN:
      SITE_DOMAIN: {{ project_name }}.docker  # Use {{ project_name }}.lvh.me for Linux
      # WSGI_ADDRESS:
    image: interaction/{{ project_name }}:latest
    links:
      # - elasticsearch
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./:/opt/{{ project_name }}
      - ./var:/opt/{{ project_name }}/var
  # elasticsearch:
  #   image: interaction/elasticsearch:1
  postgres:
    image: postgres:9.4
  redis:
    image: redis:3
