version: "2"
services:
  django:
    build: .
    command: gulp.sh
    environment:
      SITE_DOMAIN: {{ project_name }}.docker  # for OS X with Dinghy
    image: interaction/{{ project_name }}:latest
    links:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./:/opt/{{ project_name }}
      - ./var:/opt/{{ project_name }}/var
  postgres:
    image: postgres:9.4
  redis:
    image: redis:latest
