version: "2"
services:
  django:
    build: .
    command: gulp.sh
    environment:
      MASTER_PASSWORD: abc123
    image: interaction/{{ project_name }}:latest
    links:
      # - elasticsearch
      - postgres
      - redis
    ports:
      - "8000:8000"
    read_only: true
    volumes:
      - ./:/opt/{{ project_name }}
      - ~/.ssh:/opt/.ssh
  # elasticsearch:
  #   image: interaction/elasticsearch-icu:1
  postgres:
    image: onjin/alpine-postgres:9.4
  redis:
    command: redis-server --appendonly yes
    image: redis:3-alpine
