django:
  command: runtests.sh
  environment:
    TRAVIS:
  image: interaction/{{ project_name }}:${TAG}
  links:
    # - elasticsearch
    - postgres
    - redis
  read_only: true
# elasticsearch:
#   image: interaction/elasticsearch-icu:1
postgres:
  image: onjin/alpine-postgres:9.4
redis:
  command: redis-server --appendonly yes
  image: redis:3-alpine
