elasticsearch:
  image: interaction/elasticsearch-icu:1
postgres:
  image: postgres:9.4
redis:
  image: redis:3
sut:
  build: .
  command: python manage.py test -n -v 2 --noinput --settings={{ project_name }}.tests.settings
  environment:
    BASE_SETTINGS_MODULE: develop
    SITE_DOMAIN: {{ project_name }}.docker  # Use {{ project_name }}.lvh.me for Linux
    TRAVIS:
  image: interaction/{{ project_name }}:latest
  links:
    - elasticsearch
    - postgres
    - redis
  ports:
    - "8000"
  volumes:
    - ./:/opt/{{ project_name }}
    - ./var:/opt/{{ project_name }}/var
