version: "2"
services:
  django:
    build: .
    # command: gulp.sh
    command: setup-local-env.sh migrate.sh supervisor.sh
    environment:
      BASE_SETTINGS_MODULE: develop
      # EMAIL_HOST:
      # EMAIL_HOST_PASSWORD:
      # EMAIL_HOST_USER:
      # MASTER_PASSWORD:
      # MEDIA_AWS_ACCESS_KEY_ID:
      # MEDIA_AWS_SECRET_ACCESS_KEY:
      # MEDIA_AWS_STORAGE_BUCKET_NAME:
      # NEW_RELIC_CONFIG_FILE:
      # PGDATABASE:
      # PGHOST:
      # PGPASSWORD:
      # PGPORT:
      # PGUSER:
      PIP_INDEX_URL: https://devpi.ixcsandbox.com/ic/dev/+simple
      PYTHONWARNINGS: ignore
      # SENTRY_DSN:
      SITE_DOMAIN: {{ project_name }}.docker  # Use {{ project_name }}.lvh.me for Linux
      # WSGI_ADDRESS:
    image: interaction/{{ project_name }}:latest
    links:
      - elasticsearch
      - postgres
      - redis
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - ./:/opt/{{ project_name }}
      - ./var:/opt/{{ project_name }}/var
  elasticsearch:
    image: interaction/elasticsearch-icu:1
  postgres:
    image: postgres:9.4
  redis:
    image: redis:3
