version: "2"
services:
  django:
    build:
      args:
        PIP_INDEX_URL: https://devpi.ixcsandbox.com/ic/dev/+simple
      context: .
    environment:
      PGPASSWORD: database_password
      TRAVIS:
    image: interaction/{{ project_name }}:latest
    links:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - django:/opt/{{ project_name }}/var
  postgres:
    environment:
      POSTGRES_PASSWORD: database_password
    image: postgres:9.4
  redis:
    image: redis:latest
volumes:
  django: {}
